### PR TITLE
Create GCD and LCM

### PR DESCRIPTION
**Pull request by GitanshKapoor**

### CODE REVIEW

**Comment by GitanshKapoor** [comment]
to find gcd and lcm of 2 numbers

**Review by mauryahimanshu — APPROVED** [review]

**Comment by mauryahimanshu** [comment]
Thanks for Contributing @GitanshKapoor .

**Comment by GitanshKapoor** [comment]
I have contributed 3 files i hope you like my work

**Comment by GitanshKapoor** [comment]
This is my first time contributing to Hacktoberfest i am really enjoying it

**Pull request merged**
