### PR TITLE
Added the sol. of issue #2 (codes in c++)

### PR DESCRIPTION
**Pull request by ankit-kmar**
added the 'codes in c++' folder, inside which the code of fibonacci series upto n terms in added inside a separate fibonacci sequence folder.

### CODE REVIEW

**Comment by mauryahimanshu** [comment]
Please remove Codes in C++ folder and instead make fibonacci folder and its file in Number Theory Folder. And then commit. I will merge.

**Comment by ankit-kmar** [comment]
All the changes are made. You can ask for more changes if you want.

**Comment by mauryahimanshu** [comment]
Alright. Looks Good. I will merge.

**Comment by mauryahimanshu** [comment]
Thanks for contributing @ankit-kmar .

**Pull request merged**
